version: 2

jobs:
  build:
    working_directory: ~/circleci-platform-agent
    environment:
      LIBRARY: quay.io/feedyard
      CONTAINER_NAME: circleci-platform-agent
      VERSION: 3.8
      BASH_ENV: local.env
    docker:
    - image: quay.io/feedyard/circleci-base-agent
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: confirm Docker
        command: docker info
    - run:
        name: decrypt secrets
        command: openssl aes-256-cbc -d -in env.ci -out local.env -k $FEEDYARD_PIPELINE_KEY
    - run:
        name: build image
        command: docker build -t $LIBRARY/$CONTAINER_NAME:latest .
    - run:
        name: tag with build version
        command: docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
    - run:
        name: configuration tests
        command: |
          CID="$(docker run -it -d --entrypoint ash $LIBRARY/$CONTAINER_NAME:latest)"
          inspec exec profiles/$CONTAINER_NAME/ -t docker://$CID
          docker rm -f $CID
    - deploy:
        name: deploy to quay.io
        command: |
          docker login -u $FEEDYARD_CIRCLECI_QUAYIO_DEPLOY_USER -p $FEEDYARD_CIRCLECI_QUAYIO_DEPLOY_USER_TOKEN quay.io
          docker push $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
          docker push $LIBRARY/$CONTAINER_NAME:latest
